### ISSUE TITLE
Issues with downloading from fanfiction.net site

### ISSUE THREAD

**Issue by GazalBhargava** [p0ody/ff2ebook#30]
The link when entered is processed slowly and the output tab shows that the data regarding author, fandom, pairing etc can not be collected.

**Comment by spatten** [comment]
It looks like this is a general issue with fanfiction.net blocking scripts: https://github.com/JimmXinu/FanFicFare/issues/614

**Comment by maxivic** [comment]
> It looks like this is a general issue with fanfiction.net blocking scripts: [JimmXinu/FanFicFare#614](https://github.com/JimmXinu/FanFicFare/issues/614)

hello i read everything there but sorry i dont understand a thing, so should we do something for ff2ebook to work? because last week i also have the same issue and is going to submit an issue til i saw this.

edit: i checked ficsave twitter since their also having the same problem and was told it was because of ffn adding cloudfare something. so probably waiting is the best way to help
