### ISSUE TITLE
Wattpad not working 

### ISSUE THREAD

**Issue by miraxnair** [p0ody/ff2ebook#41]
Hi! I understand that you are busy but whenever you have time can you look into why downloading from wattpad isn’t working anymore? It just keeps saying failed to get fix infos. The site I’m using is  https://ff2.theyoungappy.com/ 
Thank you.

**Comment by StarWolf3000** [comment]
The fork is done by @bastien8060

**Comment by bastien8060** [comment]
Let me fix it, I just noticed it stops working. Thanks for the report !

**Comment by bastien8060** [comment]
Okay according to the logs, the issue is that the chapters link layout changed on wattpad.com, meaning ff2ebook cannot find them. I'll fix the code to look for the chapters in other way.

**Comment by bastien8060** [comment]
Sorry for the delay I took to answer btw, my timezone is quite different ...
edit: almost fixed. Fixing the chapters number detection (ff2ebook searching how many chapters there are to fetch) + getting fanfic's title

**Comment by bastien8060** [comment]
Update: its now fully working again. You can use any url eg:
- https://www.wattpad.com/445619711-the-time-machine-completed-chapter-1
- https://www.wattpad.com/445634641-the-time-machine-completed-chapter-6
- https://www.wattpad.com/story/117205261-the-time-machine-completed
- https://www.wattpad.com/story/117205261

It might be down later for a bit, since i will do some server maintenance and add http/2

I think the issue can be closed, but you can leave it open if you wish

**Comment by miraxnair** [comment]
@bastien8060 Thank you so much!

**Comment by bastien8060** [comment]
no problem

**Comment by bastien8060** [comment]
Update: it is very fast now. Before each calls where synchronous: it only fetched one chapter at a time. Now it gets all of them at the same time. 

The time it took before was `2 seconds` times `the amount of chapters`. Now its `2 seconds` for the whole fanfiction.
