### ISSUE TITLE
Chapters instead of characters

### ISSUE THREAD

**Issue by kolbdog3333** [p0ody/ff2ebook#50]
Can you fix it so if there are no characters in the fanfic it remains blank instead of number of chapters

**Comment by p0ody** [comment]
Could you provide an example please (Fic id or link) 
Thanks

**Comment by kolbdog3333** [comment]
Whenever there are no characters in a chapter in the heading like this one
https://www.fanfiction.net/s/12605611/1/The-Lion-Guard-My-Version
It shows the number of chapters instead of blank

**Comment by p0ody** [comment]
To get it fixed, i removed the pairing lookup because there is too many combination of fic "header" to match properly every time and get the result we want:

example:
1. Rated: [Fiction K+] - Spanish - Narcissa M., Druella B. - Words: 315 -   // No story type, pairing. no chapter count
2. Rated: [Fiction K+] - English - Hurt/Comfort/Friendship - Chapters: 200 - Words: 317,152 - // Story type, no pairing, chapter count
3. Rated: [Fiction T] - English - Words: 551 -  // No story type, no pairing, no chapter count
4. Rated: [Fiction T] - English - Drama/Romance - Harry P., Voldemort, Tom R. Jr., Gellert G. - Chapters: 14 - Words: 179,019 - // Story type, pairing, chapter count

And the only thing that separate each data is only "-" with no way knowing what is supposed to be between the -.

So its pretty hard to get the wanted value.

Edit:
I might add a new row in the title page instead of pairing and Fic type that will use the value between the language and the Chapter count/Words count.

Something like this using the example above:
1. **Narcissa M., Druella B.**
2. **Hurt/Comfort/Friendship**
3. blank
4. **Drama/Romance - Harry P., Voldemort, Tom R. Jr., Gellert G.**

a new row called something like "Additional information"

i think that would be a decent compromise.

**Comment by p0ody** [comment]
I might add a new row in the title page instead of pairing and Fic type that will the value between the language and the Chapter count/Words count.

Something like this using the example above:
**Narcissa M., Druella B.**
**Hurt/Comfort/Friendship**

and another example:
Rated: [Fiction T] - English - Drama/Romance - Harry P., Voldemort, Tom R. Jr., Gellert G. - Chapters: 14 - Words: 179,019 -
would look like:
**Drama/Romance - Harry P., Voldemort, Tom R. Jr., Gellert G.**

i thing that would be a decent compromise.
