### ISSUE TITLE
Pairings/Charaters fix

### ISSUE THREAD

**Issue by kolbdog3333** [p0ody/ff2ebook#58]
Hi sorry to bring this fix up so quickly after the error problem. But can you fix it so the Pairings/Characters is just blank instead of showing the amount of words or chapters here is what I mean
Fandom: my hero academia/僕のヒーローアカデミア

Summary: Izuku Midoriya, couldn't be a hero. But despite this, he soon finds he's a magnet for trouble, particularly trouble involving children. There a lot's of children in the city with quirks that cause issues for them and the people around them. And if their parent's won't care for them then he will! It may not have been the type of hero he wanted to be. But he's a hero none the less!

Pairings/Main char.: Words: 408,812

Published: 2020-06-25

Last updated: 2022-03-24

Words count: 408,812

Chapters count: 105
This is from an epub I just downloaded. The Pairings and main characters should be blank instead of having that can you fix when have the chance thanks
Sorry once again

**Comment by p0ody** [comment]
To get it fixed, i removed the pairing lookup because there is too many combination of fic "header" to match properly every time and get the result we want:

example:
Rated: [Fiction K+] - Spanish - Narcissa M., Druella B. - Words: 315 -   // No story type, pairing. no chapter count
Rated: [Fiction K+] - English - Hurt/Comfort/Friendship - Chapters: 200 - Words: 317,152 - // Story type, no pairing, chapter count
Rated: [Fiction T] - English - Words: 551 -  // No story type, no pairing, no chapter count

And the only thing that separate each data is only "-" with no way knowing what is supposed to be between the -.

So its pretty hard to get the wanted value.

**Comment by kolbdog3333** [comment]
Hey when you fixed this you removed the pairings and characters all together
So now when  there is a character or pairing there is nothing there
Here is link
https://www.fanfiction.net/s/13637186/1/Mother-Nature-s-Daughter
example
Mothers Natures Daughter
Leni L., Lincoln L is supposed to be there now nothing
