### ISSUE TITLE
error downloading fanfics again

### ISSUE THREAD

**Issue by kolbdog3333** [p0ody/ff2ebook#60]
When downloading fanfics it stops at 20 chapters then it just says
Fetching chapter 32 2/5 Error caching chapter and just continues then just fails after 100 fetches

**Comment by p0ody** [comment]
Seems like cloudflare is being more of a pain once in a while, the scraper is having difficulty.

You might want to try again later.

![image](https://user-images.githubusercontent.com/564032/160661563-d8a0062d-0a03-487d-8afe-ccb7a1577f7c.png)

**Comment by bastien8060** [comment]
im suggesting something, I think chapters should be cached. not the stories which have been cached (archived) since a long time ago. I don't know if this is already implemented, but I know for sure it wasn't. Maybe a cache at the scraper level could reduce the number of requests sent to cf.

**Comment by p0ody** [comment]
This would be a good idea, but the thing is there is no way AFAIK to know if a chapter has been modified since it has been cached.

The only thing that says a story has been modified is the Updated date, but it could be anywhere in the story.

![image](https://user-images.githubusercontent.com/564032/160849735-15fe4f75-18af-497c-b183-c43520fd5b64.png)

So if the Updated date change, it would need to update all the chapter anyway, which is pretty much what it is doing already.

BTW, i updated the scraper to wait on these new cloudflare page instead of closing ASAP and retrying, so it should have fixed the problem.
